FROM node:20-alpine

RUN apk add --no-cache openssl

WORKDIR /usr/src/app

COPY package.json pnpm-lock.yaml ./
COPY prisma ./prisma

RUN npm i pnpm -g

RUN pnpm install

COPY . .

EXPOSE 3000

CMD ["pnpm", "dev:docker"]
