import {
  sasuke,
  jiraya,
  gara,
  itachi,
  hashirama,
  kakashi,
  madara,
  lee,
  naruto,
} from './images';

export const avatarCharacters = [
  {
    id: 1,
    name: 'Itachi',
    image: itachi,
    catchphrase:
      'Creating bug-free illusions, because actually fixing them is too much effort.',
    desc: 'Ah, Itachi, the silent hero suffering for the sake of others. Your backend skills are legendary, rivaling the best in the business. Every time you touch the frontend, it’s like witnessing a master artist at work, creating interfaces so intuitive they make the rest of us look like amateurs.',
    genjutsu: 100,
    ninjutsu: 70,
    taijutsu: 60,
  },
  {
    id: 2,
    name: 'Kakashi',
    image: kakashi,
    catchphrase: 'The Copy-Paste Ninja (Sharingan = Google Search)',
    desc: 'The ‘cool’ mentor who loves to show off their battle scars. Your backend skills are solid, but your frontend work looks like it’s always in ‘copy ninja’ mode from a bad source. Clean code? Sure, if by clean you mean ‘covered up with clever hacks’.',
    genjutsu: 90,
    ninjutsu: 70,
    taijutsu: 70,
  },
  {
    id: 3,
    name: 'Lee',
    image: lee,
    catchphrase:
      "Punching hard on the push button, because git conflict's is managers problem.",
    desc: 'The overenthusiastic coder who compensates with brute force. Your backend skills are non-existent, but at least you try... really hard. Frontend? You mean the clunky, ugly UI you keep insisting is ‘efficient’? Clean code? Well, your code is as straightforward and messy as your punches.',
    genjutsu: 0,
    ninjutsu: 0,
    taijutsu: 100,
  },
  {
    id: 4,
    name: 'Jiraya',
    image: jiraya,
    catchphrase: '106cm???',
    desc: "Ah, the 'wise' mentor who's full of stories no one asked for. Your backend skills are strong, just like your ability to talk endlessly about your glory days. Frontend? More like front-wreck, am I right? And clean code? Let's just say you’re better at writing love letters than clean functions.",
    genjutsu: 30,
    ninjutsu: 70,
    taijutsu: 40,
  },
  {
    id: 5,
    name: 'Naruto',
    image: naruto,
    catchphrase: 'Better Believe It',
    desc: `Well, look at you, the outgoing 'inspirational' type who lights up the office with your... presence. 
            You're intuitive that must be why you're always dreaming up user-friendly interfaces that are, let’s be honest, a bit of a nightmare.`,
    genjutsu: 10,
    ninjutsu: 95,
    taijutsu: 85,
  },
  {
    id: 6,
    name: 'Sasuke',
    image: sasuke,
    catchphrase: 'My name is Sasuke Uchiha. I debug faster than you blink.',
    desc: "Well, aren’t you the ‘cool’ one with your brooding looks and endless complaints about bugs. Your backend skills are almost as sharp as your personality, which isn't saying much. Frontend? You mean those flashy animations that make the app crash? And clean code? Let’s just say your idea of ‘clean’ is as messy as your personal life.",
    genjutsu: 80,
    ninjutsu: 80,
    taijutsu: 90,
  },
  {
    id: 7,
    name: 'Hasirama',
    image: hashirama,
    catchphrase: 'God Mode Frameworker (Too OP to Code)',
    desc: "The ‘legendary’ coder who talks a big game about past achievements. Your backend skills are top-notch, but your front end is stuck in the past, just like your stories. And clean code? Let's say your definition of 'clean' includes a lot of sweeping things under the rug.",
    genjutsu: 30,
    ninjutsu: 100,
    taijutsu: 90,
  },
  {
    id: 8,
    name: 'Madara',
    image: madara,
    catchphrase: 'Better Believe It',
    desc: 'The self-proclaimed ‘greatest’ who thinks they’re better than everyone. Your backend skills are unmatched, but your frontend is as dark and twisted as your ambitions. And clean code? Your idea of clean is wiping out all other codebases.',
    genjutsu: 100,
    ninjutsu: 90,
    taijutsu: 90,
  },
  {
    id: 9,
    name: 'Gaara',
    image: gara,
    catchphrase:
      'Social Anxiety Sand Coffin: The Ultimate Way to Avoid Awkward Social Interactions',
    desc: "The silent type who thinks working solo is the solution to everything. Your backend skills are decent, but don't expect your interfaces to be user-friendly – or even functional. And clean code? Well, your code is as chaotic as your sandstorms, and just as hard to navigate.",
    genjutsu: 30,
    ninjutsu: 85,
    taijutsu: 45,
  },
];
